-- +migrate Up
CREATE TABLE IF NOT EXISTS "storage_file" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "folder_id" BIGINT,
    "name" VARCHAR(255) NOT NULL,
    "file_url" VARCHAR(512) NOT NULL,
    "mime_type" VARCHAR(100) NOT NULL,
    "size_bytes" BIGINT NOT NULL,
    "created_by_id" BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS storage_file_created_by_id_idx ON "storage_file" ("created_by_id");
CREATE TABLE IF NOT EXISTS "violation_type" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT NOT NULL,
    "sp_level" VARCHAR(20) NOT NULL
);
ALTER TABLE "storage_file" ADD CONSTRAINT "storage_file_created_by_id_fk" FOREIGN KEY ("created_by_id") REFERENCES "user"("id");
ALTER TABLE "announcement" ADD COLUMN "banner_url" VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE "finance_transaction" ADD COLUMN "receipt_url" VARCHAR(255) NOT NULL DEFAULT '';

-- +migrate Down
DROP TABLE IF EXISTS "storage_file";
DROP TABLE IF EXISTS "violation_type";
ALTER TABLE "announcement" DROP COLUMN IF EXISTS "banner_url";
ALTER TABLE "finance_transaction" DROP COLUMN IF EXISTS "receipt_url";
