// Code generated by gokil generateroutes; DO NOT EDIT.

package app

import (
	app_announcements "backend/app/announcements"
	app_announcements_id "backend/app/announcements/_id"
	app_announcements_id_attachments "backend/app/announcements/_id/attachments"
	app_attendance_permission_requests "backend/app/attendance/permission_requests"
	app_attendance_permission_requests_id "backend/app/attendance/permission_requests/_id"
	app_auth_login "backend/app/auth/login"
	app_auth_logout "backend/app/auth/logout"
	app_auth_register "backend/app/auth/register"
	app_backup "backend/app/backup"
	app_divisions "backend/app/divisions"
	app_divisions_id "backend/app/divisions/_id"
	app_events "backend/app/events"
	app_events_id "backend/app/events/_id"
	app_events_id_attendance "backend/app/events/_id/attendance"
	app_events_id_attendance_me "backend/app/events/_id/attendance/me"
	app_events_id_recap "backend/app/events/_id/recap"
	app_finance_categories "backend/app/finance_categories"
	app_finance_categories_id "backend/app/finance_categories/_id"
	app_finance_transactions "backend/app/finance_transactions"
	app_finance_transactions_id "backend/app/finance_transactions/_id"
	app_finance_transactions_dashboard "backend/app/finance_transactions/dashboard"
	app_finance_transactions_summary "backend/app/finance_transactions/summary"
	app_letter_categories "backend/app/letter_categories"
	app_letter_categories_id "backend/app/letter_categories/_id"
	app_letter_categories_id_preview_number "backend/app/letter_categories/_id/preview_number"
	app_letter_templates "backend/app/letter_templates"
	app_letter_templates_id "backend/app/letter_templates/_id"
	app_letter_templates_id_variables "backend/app/letter_templates/_id/variables"
	app_letters "backend/app/letters"
	app_letters_id "backend/app/letters/_id"
	app_letters_id_download "backend/app/letters/_id/download"
	app_letters_bulk_delete "backend/app/letters/bulk_delete"
	app_letters_export "backend/app/letters/export"
	app_letters_parse_incoming "backend/app/letters/parse_incoming"
	app_me "backend/app/me"
	app_me_avatar "backend/app/me/avatar"
	app_me_password "backend/app/me/password"
	app_me_permissions "backend/app/me/permissions"
	app_permission_requests "backend/app/permission_requests"
	app_permission_requests_me "backend/app/permission_requests/me"
	app_permissions "backend/app/permissions"
	app_public_recruitment_slug "backend/app/public/recruitment/_slug"
	app_public_recruitment_slug_submit "backend/app/public/recruitment/_slug/submit"
	app_push_subscribe "backend/app/push/subscribe"
	app_recruitments "backend/app/recruitments"
	app_recruitments_id "backend/app/recruitments/_id"
	app_recruitments_id_submissions "backend/app/recruitments/_id/submissions"
	app_roles "backend/app/roles"
	app_roles_id "backend/app/roles/_id"
	app_roles_id_permissions "backend/app/roles/_id/permissions"
	app_settings "backend/app/settings"
	app_storage_files "backend/app/storage/files"
	app_storage_files_id "backend/app/storage/files/_id"
	app_storage_folders "backend/app/storage/folders"
	app_users "backend/app/users"
	app_users_id "backend/app/users/_id"
	app_users_id_avatar "backend/app/users/_id/avatar"
	app_users_id_password "backend/app/users/_id/password"
	app_users_import "backend/app/users/import"
	app_users_import_template "backend/app/users/import/template"
	app_violation_types "backend/app/violation_types"
	app_violation_types_id "backend/app/violation_types/_id"
	app_violations "backend/app/violations"
	app_violations_id "backend/app/violations/_id"
	"github.com/lrndwy/gokil/framework"
)

func init() {
	framework.RegisterRoute("GET", "/announcements", app_announcements.GET)
	framework.RegisterRoute("POST", "/announcements", app_announcements.POST)
	framework.RegisterRoute("PUT", "/announcements/:id", app_announcements_id.PUT)
	framework.RegisterRoute("DELETE", "/announcements/:id", app_announcements_id.DELETE)
	framework.RegisterRoute("GET", "/announcements/:id/attachments", app_announcements_id_attachments.GET)
	framework.RegisterRoute("GET", "/attendance/permission_requests", app_attendance_permission_requests.GET)
	framework.RegisterRoute("PUT", "/attendance/permission_requests/:id", app_attendance_permission_requests_id.PUT)
	framework.RegisterRoute("POST", "/auth/login", app_auth_login.POST)
	framework.RegisterRoute("POST", "/auth/logout", app_auth_logout.POST)
	framework.RegisterRoute("POST", "/auth/register", app_auth_register.POST)
	framework.RegisterRoute("GET", "/backup", app_backup.GET)
	framework.RegisterRoute("POST", "/backup", app_backup.POST)
	framework.RegisterRoute("GET", "/divisions", app_divisions.GET)
	framework.RegisterRoute("POST", "/divisions", app_divisions.POST)
	framework.RegisterRoute("PUT", "/divisions/:id", app_divisions_id.PUT)
	framework.RegisterRoute("DELETE", "/divisions/:id", app_divisions_id.DELETE)
	framework.RegisterRoute("GET", "/events", app_events.GET)
	framework.RegisterRoute("POST", "/events", app_events.POST)
	framework.RegisterRoute("GET", "/events/:id", app_events_id.GET)
	framework.RegisterRoute("PUT", "/events/:id", app_events_id.PUT)
	framework.RegisterRoute("DELETE", "/events/:id", app_events_id.DELETE)
	framework.RegisterRoute("POST", "/events/:id/attendance", app_events_id_attendance.POST)
	framework.RegisterRoute("GET", "/events/:id/attendance/me", app_events_id_attendance_me.GET)
	framework.RegisterRoute("GET", "/events/:id/recap", app_events_id_recap.GET)
	framework.RegisterRoute("GET", "/finance_categories", app_finance_categories.GET)
	framework.RegisterRoute("POST", "/finance_categories", app_finance_categories.POST)
	framework.RegisterRoute("PUT", "/finance_categories/:id", app_finance_categories_id.PUT)
	framework.RegisterRoute("DELETE", "/finance_categories/:id", app_finance_categories_id.DELETE)
	framework.RegisterRoute("GET", "/finance_transactions", app_finance_transactions.GET)
	framework.RegisterRoute("POST", "/finance_transactions", app_finance_transactions.POST)
	framework.RegisterRoute("PUT", "/finance_transactions/:id", app_finance_transactions_id.PUT)
	framework.RegisterRoute("DELETE", "/finance_transactions/:id", app_finance_transactions_id.DELETE)
	framework.RegisterRoute("GET", "/finance_transactions/dashboard", app_finance_transactions_dashboard.GET)
	framework.RegisterRoute("GET", "/finance_transactions/summary", app_finance_transactions_summary.GET)
	framework.RegisterRoute("GET", "/letter_categories", app_letter_categories.GET)
	framework.RegisterRoute("POST", "/letter_categories", app_letter_categories.POST)
	framework.RegisterRoute("PUT", "/letter_categories/:id", app_letter_categories_id.PUT)
	framework.RegisterRoute("DELETE", "/letter_categories/:id", app_letter_categories_id.DELETE)
	framework.RegisterRoute("POST", "/letter_categories/:id/preview_number", app_letter_categories_id_preview_number.POST)
	framework.RegisterRoute("GET", "/letter_templates", app_letter_templates.GET)
	framework.RegisterRoute("POST", "/letter_templates", app_letter_templates.POST)
	framework.RegisterRoute("PUT", "/letter_templates/:id", app_letter_templates_id.PUT)
	framework.RegisterRoute("DELETE", "/letter_templates/:id", app_letter_templates_id.DELETE)
	framework.RegisterRoute("GET", "/letter_templates/:id/variables", app_letter_templates_id_variables.GET)
	framework.RegisterRoute("GET", "/letters", app_letters.GET)
	framework.RegisterRoute("POST", "/letters", app_letters.POST)
	framework.RegisterRoute("GET", "/letters/:id", app_letters_id.GET)
	framework.RegisterRoute("PUT", "/letters/:id", app_letters_id.PUT)
	framework.RegisterRoute("DELETE", "/letters/:id", app_letters_id.DELETE)
	framework.RegisterRoute("GET", "/letters/:id/download", app_letters_id_download.GET)
	framework.RegisterRoute("POST", "/letters/bulk_delete", app_letters_bulk_delete.POST)
	framework.RegisterRoute("GET", "/letters/export", app_letters_export.GET)
	framework.RegisterRoute("POST", "/letters/parse_incoming", app_letters_parse_incoming.POST)
	framework.RegisterRoute("GET", "/me", app_me.GET)
	framework.RegisterRoute("PUT", "/me", app_me.PUT)
	framework.RegisterRoute("POST", "/me/avatar", app_me_avatar.POST)
	framework.RegisterRoute("PUT", "/me/password", app_me_password.PUT)
	framework.RegisterRoute("GET", "/me/permissions", app_me_permissions.GET)
	framework.RegisterRoute("POST", "/permission_requests", app_permission_requests.POST)
	framework.RegisterRoute("GET", "/permission_requests/me", app_permission_requests_me.GET)
	framework.RegisterRoute("GET", "/permissions", app_permissions.GET)
	framework.RegisterRoute("GET", "/public/recruitment/:slug", app_public_recruitment_slug.GET)
	framework.RegisterRoute("POST", "/public/recruitment/:slug/submit", app_public_recruitment_slug_submit.POST)
	framework.RegisterRoute("GET", "/push/subscribe", app_push_subscribe.GET)
	framework.RegisterRoute("POST", "/push/subscribe", app_push_subscribe.POST)
	framework.RegisterRoute("DELETE", "/push/subscribe", app_push_subscribe.DELETE)
	framework.RegisterRoute("GET", "/recruitments", app_recruitments.GET)
	framework.RegisterRoute("POST", "/recruitments", app_recruitments.POST)
	framework.RegisterRoute("PUT", "/recruitments/:id", app_recruitments_id.PUT)
	framework.RegisterRoute("GET", "/recruitments/:id/submissions", app_recruitments_id_submissions.GET)
	framework.RegisterRoute("GET", "/roles", app_roles.GET)
	framework.RegisterRoute("POST", "/roles", app_roles.POST)
	framework.RegisterRoute("PUT", "/roles/:id", app_roles_id.PUT)
	framework.RegisterRoute("DELETE", "/roles/:id", app_roles_id.DELETE)
	framework.RegisterRoute("GET", "/roles/:id/permissions", app_roles_id_permissions.GET)
	framework.RegisterRoute("PUT", "/roles/:id/permissions", app_roles_id_permissions.PUT)
	framework.RegisterRoute("GET", "/settings", app_settings.GET)
	framework.RegisterRoute("PUT", "/settings", app_settings.PUT)
	framework.RegisterRoute("GET", "/storage/files", app_storage_files.GET)
	framework.RegisterRoute("POST", "/storage/files", app_storage_files.POST)
	framework.RegisterRoute("DELETE", "/storage/files/:id", app_storage_files_id.DELETE)
	framework.RegisterRoute("GET", "/storage/folders", app_storage_folders.GET)
	framework.RegisterRoute("POST", "/storage/folders", app_storage_folders.POST)
	framework.RegisterRoute("GET", "/users", app_users.GET)
	framework.RegisterRoute("POST", "/users", app_users.POST)
	framework.RegisterRoute("GET", "/users/:id", app_users_id.GET)
	framework.RegisterRoute("PUT", "/users/:id", app_users_id.PUT)
	framework.RegisterRoute("DELETE", "/users/:id", app_users_id.DELETE)
	framework.RegisterRoute("POST", "/users/:id/avatar", app_users_id_avatar.POST)
	framework.RegisterRoute("PUT", "/users/:id/password", app_users_id_password.PUT)
	framework.RegisterRoute("POST", "/users/import", app_users_import.POST)
	framework.RegisterRoute("GET", "/users/import/template", app_users_import_template.GET)
	framework.RegisterRoute("GET", "/violation_types", app_violation_types.GET)
	framework.RegisterRoute("POST", "/violation_types", app_violation_types.POST)
	framework.RegisterRoute("PUT", "/violation_types/:id", app_violation_types_id.PUT)
	framework.RegisterRoute("DELETE", "/violation_types/:id", app_violation_types_id.DELETE)
	framework.RegisterRoute("GET", "/violations", app_violations.GET)
	framework.RegisterRoute("POST", "/violations", app_violations.POST)
	framework.RegisterRoute("DELETE", "/violations/:id", app_violations_id.DELETE)
}
